// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
INSERT INTO feed_follows (id, user_id, feed_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, feed_id, created_at, updated_at
`

type CreateFeedFollowParams struct {
	ID        int32
	UserID    int32
	FeedID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedFollowByUser = `-- name: DeleteFeedFollowByUser :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowByUserParams struct {
	UserID int32
	FeedID int32
}

func (q *Queries) DeleteFeedFollowByUser(ctx context.Context, arg DeleteFeedFollowByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByUser, arg.UserID, arg.FeedID)
	return err
}

const getFeedFollowByUser = `-- name: GetFeedFollowByUser :many
SELECT id, user_id, feed_id, created_at, updated_at FROM feed_follows WHERE user_id = $1
`

func (q *Queries) GetFeedFollowByUser(ctx context.Context, userID int32) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
